run:
  build-tags:
    - generator

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - gocognit
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  gocognit:
    min-complexity: 25
  goconst:
    min-len: 2
    min-occurrences: 2
  govet:
    check-shadowing: true
  lll:
    line-length: 120
    tab-width: 4

issues:
  exclude-use-default: false
