version: 3

vars:
  GEN_OUT_DIR: handler
  MOCKERY_VERSION: v3.5.5

tasks:
  fmt-imports:
    # macOS requires to install GNU sed first. Use `brew install gnu-sed` to install it.
    # It has to be added to PATH as `sed` command, to replace default BSD sed.
    # See `brew info gnu-sed` for more details on how to add it to PATH.
    # /^import ($$/: starts with "import ("
    # /^)/: ends with ")"
    # /^[[:space:]]*$$/: empty lines
    cmds:
      - find . -type f -name '*.go' -exec sed -i '/^import ($$/,/^)/ {/^[[:space:]]*$$/d}' {} +
      - goimports -local "github.com/aiven/go-client-codegen" -w .
  get-openapi-spec:
    cmds:
      - curl -s -o openapi.json https://api.aiven.io/doc/openapi.json
  go-generate:
    cmds:
      - rm -rf {{.GEN_OUT_DIR}}
      - GEN_OUT_DIR={{.GEN_OUT_DIR}} go run -tags=generator ./generator/...
      - task: fmt-imports
    requires:
      vars:
        - GEN_OUT_DIR
  generate-mocks:
    preconditions:
      - sh: command -v mockery
        msg: "mockery is not installed. Install it with: go install github.com/vektra/mockery/v3@{{.MOCKERY_VERSION}}"
    cmds:
      - mockery
  generate:
    cmds:
      - task: get-openapi-spec
      - task: go-generate
      - task: generate-mocks
  test:
    cmds:
      - go test -v
