// Code generated by Aiven. DO NOT EDIT.

package staticip

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
)

type Handler interface {
	// ProjectStaticIPAssociate associate a static IP address with a service
	// POST /v1/project/{project}/static-ips/{static_ip_address_id}/association
	// https://api.aiven.io/doc/#tag/StaticIP/operation/ProjectStaticIPAssociate
	// Required roles or permissions: service:configuration:write
	ProjectStaticIPAssociate(ctx context.Context, project string, staticIpaddressId string, in *ProjectStaticIPAssociateIn) (*ProjectStaticIPAssociateOut, error)

	// ProjectStaticIPAvailabilityList list static IP address cloud availability and prices for a project
	// GET /v1/project/{project}/static-ip-availability
	// https://api.aiven.io/doc/#tag/StaticIP/operation/ProjectStaticIPAvailabilityList
	// Required roles or permissions: developer, operator, read_only
	ProjectStaticIPAvailabilityList(ctx context.Context, project string) ([]StaticIPAddressAvailabilityOut, error)

	// ProjectStaticIPDissociate dissociate a static IP address from a service
	// DELETE /v1/project/{project}/static-ips/{static_ip_address_id}/association
	// https://api.aiven.io/doc/#tag/StaticIP/operation/ProjectStaticIPDissociate
	// Required roles or permissions: service:configuration:write
	ProjectStaticIPDissociate(ctx context.Context, project string, staticIpaddressId string) (*ProjectStaticIPDissociateOut, error)

	// ProjectStaticIPPatch update a static IP address configuration
	// PATCH /v1/project/{project}/static-ips/{static_ip_address_id}
	// https://api.aiven.io/doc/#tag/StaticIP/operation/ProjectStaticIPPatch
	// Required roles or permissions: operator
	ProjectStaticIPPatch(ctx context.Context, project string, staticIpaddressId string, in *ProjectStaticIPPatchIn) (*ProjectStaticIPPatchOut, error)

	// PublicStaticIPAvailabilityList list static IP clouds and prices
	// GET /v1/tenants/{tenant}/static-ip-availability
	// https://api.aiven.io/doc/#tag/Cloud_platforms/operation/PublicStaticIPAvailabilityList
	PublicStaticIPAvailabilityList(ctx context.Context, tenant string) ([]StaticIPAddressAvailabilityOut, error)

	// StaticIPCreate create static IP address
	// POST /v1/project/{project}/static-ips
	// https://api.aiven.io/doc/#tag/StaticIP/operation/StaticIPCreate
	// Required roles or permissions: operator
	StaticIPCreate(ctx context.Context, project string, in *StaticIPCreateIn) (*StaticIPCreateOut, error)

	// StaticIPDelete delete a static IP address
	// DELETE /v1/project/{project}/static-ips/{static_ip_address_id}
	// https://api.aiven.io/doc/#tag/StaticIP/operation/StaticIPDelete
	StaticIPDelete(ctx context.Context, project string, staticIpaddressId string) (*StaticIPDeleteOut, error)

	// StaticIPList list static IP addresses
	// GET /v1/project/{project}/static-ips
	// https://api.aiven.io/doc/#tag/StaticIP/operation/StaticIPList
	// Required roles or permissions: developer, operator, read_only
	StaticIPList(ctx context.Context, project string) ([]StaticIPOut, error)
}

// doer http client
type doer interface {
	Do(ctx context.Context, operationID, method, path string, in any, query ...[2]string) ([]byte, error)
}

func NewHandler(doer doer) StaticIPHandler {
	return StaticIPHandler{doer}
}

type StaticIPHandler struct {
	doer doer
}

func (h *StaticIPHandler) ProjectStaticIPAssociate(ctx context.Context, project string, staticIpaddressId string, in *ProjectStaticIPAssociateIn) (*ProjectStaticIPAssociateOut, error) {
	path := fmt.Sprintf("/v1/project/%s/static-ips/%s/association", url.PathEscape(project), url.PathEscape(staticIpaddressId))
	b, err := h.doer.Do(ctx, "ProjectStaticIPAssociate", "POST", path, in)
	if err != nil {
		return nil, err
	}
	out := new(ProjectStaticIPAssociateOut)
	err = json.Unmarshal(b, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (h *StaticIPHandler) ProjectStaticIPAvailabilityList(ctx context.Context, project string) ([]StaticIPAddressAvailabilityOut, error) {
	path := fmt.Sprintf("/v1/project/%s/static-ip-availability", url.PathEscape(project))
	b, err := h.doer.Do(ctx, "ProjectStaticIPAvailabilityList", "GET", path, nil)
	if err != nil {
		return nil, err
	}
	out := new(projectStaticIPAvailabilityListOut)
	err = json.Unmarshal(b, out)
	if err != nil {
		return nil, err
	}
	return out.StaticIPAddressAvailability, nil
}
func (h *StaticIPHandler) ProjectStaticIPDissociate(ctx context.Context, project string, staticIpaddressId string) (*ProjectStaticIPDissociateOut, error) {
	path := fmt.Sprintf("/v1/project/%s/static-ips/%s/association", url.PathEscape(project), url.PathEscape(staticIpaddressId))
	b, err := h.doer.Do(ctx, "ProjectStaticIPDissociate", "DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	out := new(ProjectStaticIPDissociateOut)
	err = json.Unmarshal(b, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (h *StaticIPHandler) ProjectStaticIPPatch(ctx context.Context, project string, staticIpaddressId string, in *ProjectStaticIPPatchIn) (*ProjectStaticIPPatchOut, error) {
	path := fmt.Sprintf("/v1/project/%s/static-ips/%s", url.PathEscape(project), url.PathEscape(staticIpaddressId))
	b, err := h.doer.Do(ctx, "ProjectStaticIPPatch", "PATCH", path, in)
	if err != nil {
		return nil, err
	}
	out := new(ProjectStaticIPPatchOut)
	err = json.Unmarshal(b, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (h *StaticIPHandler) PublicStaticIPAvailabilityList(ctx context.Context, tenant string) ([]StaticIPAddressAvailabilityOut, error) {
	path := fmt.Sprintf("/v1/tenants/%s/static-ip-availability", url.PathEscape(tenant))
	b, err := h.doer.Do(ctx, "PublicStaticIPAvailabilityList", "GET", path, nil)
	if err != nil {
		return nil, err
	}
	out := new(publicStaticIPAvailabilityListOut)
	err = json.Unmarshal(b, out)
	if err != nil {
		return nil, err
	}
	return out.StaticIPAddressAvailability, nil
}
func (h *StaticIPHandler) StaticIPCreate(ctx context.Context, project string, in *StaticIPCreateIn) (*StaticIPCreateOut, error) {
	path := fmt.Sprintf("/v1/project/%s/static-ips", url.PathEscape(project))
	b, err := h.doer.Do(ctx, "StaticIPCreate", "POST", path, in)
	if err != nil {
		return nil, err
	}
	out := new(StaticIPCreateOut)
	err = json.Unmarshal(b, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (h *StaticIPHandler) StaticIPDelete(ctx context.Context, project string, staticIpaddressId string) (*StaticIPDeleteOut, error) {
	path := fmt.Sprintf("/v1/project/%s/static-ips/%s", url.PathEscape(project), url.PathEscape(staticIpaddressId))
	b, err := h.doer.Do(ctx, "StaticIPDelete", "DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	out := new(StaticIPDeleteOut)
	err = json.Unmarshal(b, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (h *StaticIPHandler) StaticIPList(ctx context.Context, project string) ([]StaticIPOut, error) {
	path := fmt.Sprintf("/v1/project/%s/static-ips", url.PathEscape(project))
	b, err := h.doer.Do(ctx, "StaticIPList", "GET", path, nil)
	if err != nil {
		return nil, err
	}
	out := new(staticIPListOut)
	err = json.Unmarshal(b, out)
	if err != nil {
		return nil, err
	}
	return out.StaticIps, nil
}

// ProjectStaticIPAssociateIn ProjectStaticIPAssociateRequestBody
type ProjectStaticIPAssociateIn struct {
	ServiceName string `json:"service_name"` // Service name
}

// ProjectStaticIPAssociateOut ProjectStaticIPAssociateResponse
type ProjectStaticIPAssociateOut struct {
	CloudName             string                            `json:"cloud_name"`             // Target cloud
	IPAddress             string                            `json:"ip_address"`             // IPv4 address
	ServiceName           string                            `json:"service_name"`           // Service name
	State                 ProjectStaticIPAssociateStateType `json:"state"`                  // Static IP address state
	StaticIPAddressId     string                            `json:"static_ip_address_id"`   // Static IP address identifier
	TerminationProtection bool                              `json:"termination_protection"` // Static IP address is protected against deletion
}
type ProjectStaticIPAssociateStateType string

const (
	ProjectStaticIPAssociateStateTypeAssigned  ProjectStaticIPAssociateStateType = "assigned"
	ProjectStaticIPAssociateStateTypeAvailable ProjectStaticIPAssociateStateType = "available"
	ProjectStaticIPAssociateStateTypeCreated   ProjectStaticIPAssociateStateType = "created"
	ProjectStaticIPAssociateStateTypeCreating  ProjectStaticIPAssociateStateType = "creating"
	ProjectStaticIPAssociateStateTypeDeleted   ProjectStaticIPAssociateStateType = "deleted"
	ProjectStaticIPAssociateStateTypeDeleting  ProjectStaticIPAssociateStateType = "deleting"
)

func ProjectStaticIPAssociateStateTypeChoices() []string {
	return []string{"assigned", "available", "created", "creating", "deleted", "deleting"}
}

// ProjectStaticIPDissociateOut ProjectStaticIPDissociateResponse
type ProjectStaticIPDissociateOut struct {
	CloudName             string                             `json:"cloud_name"`             // Target cloud
	IPAddress             string                             `json:"ip_address"`             // IPv4 address
	ServiceName           string                             `json:"service_name"`           // Service name
	State                 ProjectStaticIPDissociateStateType `json:"state"`                  // Static IP address state
	StaticIPAddressId     string                             `json:"static_ip_address_id"`   // Static IP address identifier
	TerminationProtection bool                               `json:"termination_protection"` // Static IP address is protected against deletion
}
type ProjectStaticIPDissociateStateType string

const (
	ProjectStaticIPDissociateStateTypeAssigned  ProjectStaticIPDissociateStateType = "assigned"
	ProjectStaticIPDissociateStateTypeAvailable ProjectStaticIPDissociateStateType = "available"
	ProjectStaticIPDissociateStateTypeCreated   ProjectStaticIPDissociateStateType = "created"
	ProjectStaticIPDissociateStateTypeCreating  ProjectStaticIPDissociateStateType = "creating"
	ProjectStaticIPDissociateStateTypeDeleted   ProjectStaticIPDissociateStateType = "deleted"
	ProjectStaticIPDissociateStateTypeDeleting  ProjectStaticIPDissociateStateType = "deleting"
)

func ProjectStaticIPDissociateStateTypeChoices() []string {
	return []string{"assigned", "available", "created", "creating", "deleted", "deleting"}
}

// ProjectStaticIPPatchIn ProjectStaticIPPatchRequestBody
type ProjectStaticIPPatchIn struct {
	TerminationProtection *bool `json:"termination_protection,omitempty"` // Static IP address is protected against deletion
}

// ProjectStaticIPPatchOut ProjectStaticIPPatchResponse
type ProjectStaticIPPatchOut struct {
	CloudName             string                        `json:"cloud_name"`             // Target cloud
	IPAddress             string                        `json:"ip_address"`             // IPv4 address
	ServiceName           string                        `json:"service_name"`           // Service name
	State                 ProjectStaticIPPatchStateType `json:"state"`                  // Static IP address state
	StaticIPAddressId     string                        `json:"static_ip_address_id"`   // Static IP address identifier
	TerminationProtection bool                          `json:"termination_protection"` // Static IP address is protected against deletion
}
type ProjectStaticIPPatchStateType string

const (
	ProjectStaticIPPatchStateTypeAssigned  ProjectStaticIPPatchStateType = "assigned"
	ProjectStaticIPPatchStateTypeAvailable ProjectStaticIPPatchStateType = "available"
	ProjectStaticIPPatchStateTypeCreated   ProjectStaticIPPatchStateType = "created"
	ProjectStaticIPPatchStateTypeCreating  ProjectStaticIPPatchStateType = "creating"
	ProjectStaticIPPatchStateTypeDeleted   ProjectStaticIPPatchStateType = "deleted"
	ProjectStaticIPPatchStateTypeDeleting  ProjectStaticIPPatchStateType = "deleting"
)

func ProjectStaticIPPatchStateTypeChoices() []string {
	return []string{"assigned", "available", "created", "creating", "deleted", "deleting"}
}

type StaticIPAddressAvailabilityOut struct {
	CloudName string `json:"cloud_name"` // Target cloud
	PriceUsd  string `json:"price_usd"`  // Hourly static IP address price in this cloud region
}

// StaticIPCreateIn StaticIPCreateRequestBody
type StaticIPCreateIn struct {
	CloudName             string `json:"cloud_name"`                       // Target cloud
	TerminationProtection *bool  `json:"termination_protection,omitempty"` // Static IP address is protected against deletion
}

// StaticIPCreateOut StaticIPCreateResponse
type StaticIPCreateOut struct {
	CloudName             string            `json:"cloud_name"`             // Target cloud
	IPAddress             string            `json:"ip_address"`             // IPv4 address
	ServiceName           string            `json:"service_name"`           // Service name
	State                 StaticIPStateType `json:"state"`                  // Static IP address state
	StaticIPAddressId     string            `json:"static_ip_address_id"`   // Static IP address identifier
	TerminationProtection bool              `json:"termination_protection"` // Static IP address is protected against deletion
}

// StaticIPDeleteOut StaticIPDeleteResponse
type StaticIPDeleteOut struct {
	CloudName             string            `json:"cloud_name"`             // Target cloud
	IPAddress             string            `json:"ip_address"`             // IPv4 address
	ServiceName           string            `json:"service_name"`           // Service name
	State                 StaticIPStateType `json:"state"`                  // Static IP address state
	StaticIPAddressId     string            `json:"static_ip_address_id"`   // Static IP address identifier
	TerminationProtection bool              `json:"termination_protection"` // Static IP address is protected against deletion
}
type StaticIPOut struct {
	CloudName             string            `json:"cloud_name"`             // Target cloud
	IPAddress             string            `json:"ip_address"`             // IPv4 address
	ServiceName           string            `json:"service_name"`           // Service name
	State                 StaticIPStateType `json:"state"`                  // Static IP address state
	StaticIPAddressId     string            `json:"static_ip_address_id"`   // Static IP address identifier
	TerminationProtection bool              `json:"termination_protection"` // Static IP address is protected against deletion
}
type StaticIPStateType string

const (
	StaticIPStateTypeAssigned  StaticIPStateType = "assigned"
	StaticIPStateTypeAvailable StaticIPStateType = "available"
	StaticIPStateTypeCreated   StaticIPStateType = "created"
	StaticIPStateTypeCreating  StaticIPStateType = "creating"
	StaticIPStateTypeDeleted   StaticIPStateType = "deleted"
	StaticIPStateTypeDeleting  StaticIPStateType = "deleting"
)

func StaticIPStateTypeChoices() []string {
	return []string{"assigned", "available", "created", "creating", "deleted", "deleting"}
}

// projectStaticIPAvailabilityListOut ProjectStaticIPAvailabilityListResponse
type projectStaticIPAvailabilityListOut struct {
	StaticIPAddressAvailability []StaticIPAddressAvailabilityOut `json:"static_ip_address_availability"` // Paginated array
}

// publicStaticIPAvailabilityListOut PublicStaticIPAvailabilityListResponse
type publicStaticIPAvailabilityListOut struct {
	StaticIPAddressAvailability []StaticIPAddressAvailabilityOut `json:"static_ip_address_availability"` // Paginated array
}

// staticIPListOut StaticIPListResponse
type staticIPListOut struct {
	StaticIps []StaticIPOut `json:"static_ips"` // Paginated array
}
