name: Upgrade Trunk

on:
  schedule:
    - cron: 0 8 * * 1
  workflow_dispatch: {}

permissions: read-all

jobs:
  trunk_upgrade:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: trunk-io/trunk-action/upgrade@v1
        with:
          prefix: "ci(deps): "
          lowercase-title: true
